#nullable enable

using System;
using System.IO;
using UnityEngine;

namespace Nex.BilliardRogue.Editor
{
    /// <summary>
    /// JsonUtility mirror of Tools/Blender/environment/layouts.json (generated by make_layouts.py): per-act dressing
    /// in the arena frame of TDD §14.1, surfaces, ground tiles, lighting presets, god-ray shafts and point lights.
    /// Only the fields EnvironmentBuilder reads are declared.
    /// </summary>
    [Serializable]
    public sealed class EnvironmentLayout
    {
        public const string RelativePath = "Tools/Blender/environment/layouts.json";

        public int version;
        public LayoutAct[] acts = Array.Empty<LayoutAct>();

        /// <summary>Absolute path of layouts.json (the repository root is the Unity project's parent folder).</summary>
        public static string FilePath => Path.GetFullPath(Path.Combine(Application.dataPath, "..", "..", RelativePath));

        public static EnvironmentLayout? Load(out string error)
        {
            var path = FilePath;
            if (!File.Exists(path))
            {
                error = $"{path} not found";
                return null;
            }

            error = "";
            return JsonUtility.FromJson<EnvironmentLayout>(File.ReadAllText(path));
        }

        public LayoutAct? Act(int id)
        {
            foreach (var act in acts)
            {
                if (act.id == id) return act;
            }

            return null;
        }

        public static Vector3 Vec(float[]? values, Vector3 fallback)
        {
            return values is { Length: >= 3 } ? new Vector3(values[0], values[1], values[2]) : fallback;
        }

        public static Color Col(float[]? values, Color fallback)
        {
            return values is { Length: >= 3 } ? new Color(values[0], values[1], values[2], 1f) : fallback;
        }
    }

    [Serializable]
    public sealed class LayoutAct
    {
        public int id;
        public string name = "";
        public LayoutSurface[] surfaces = Array.Empty<LayoutSurface>();
        public LayoutGround ground = new();
        public LayoutLighting lighting = new();
        public LayoutProp[] props = Array.Empty<LayoutProp>();
        public LayoutPointLight[] pointLights = Array.Empty<LayoutPointLight>();

        /// <summary>Surface name for piece/part, or "" when the act does not list one.</summary>
        public string SurfaceFor(string piece, string part)
        {
            foreach (var surface in surfaces)
            {
                if (surface.piece == piece && surface.part == part) return surface.surface;
            }

            return "";
        }
    }

    [Serializable]
    public sealed class LayoutSurface
    {
        public string piece = "";
        public string part = "";
        public string surface = "";
    }

    [Serializable]
    public sealed class LayoutGround
    {
        public string piece = "";
        public float y;
        public float tileSize = 4f;
        public string surface = "";
        public LayoutGroundTile[] tiles = Array.Empty<LayoutGroundTile>();
    }

    [Serializable]
    public sealed class LayoutGroundTile
    {
        public float x;
        public float z;
        public float rotY;
    }

    [Serializable]
    public sealed class LayoutLighting
    {
        public LayoutPreset preset = new();
    }

    /// <summary>Field names match ActLightingPreset (layouts.json "lighting.preset").</summary>
    [Serializable]
    public sealed class LayoutPreset
    {
        public float[] sunColor = Array.Empty<float>();
        public float sunIntensity;
        public float[] sunEuler = Array.Empty<float>();
        public float[] ambientSky = Array.Empty<float>();
        public float[] ambientEquator = Array.Empty<float>();
        public float[] ambientGround = Array.Empty<float>();
        public float[] fogColor = Array.Empty<float>();
        public float fogDensity;
        public float[] rimColor = Array.Empty<float>();
        public float[] additionalLightTint = Array.Empty<float>();
        public float[] godRayColor = Array.Empty<float>();
        public float godRayIntensity;
        public float[] particleTint = Array.Empty<float>();

        public bool IsValid => sunColor.Length >= 3 && sunEuler.Length >= 3;

        /// <summary>Copies the art-directed values over target (fields the layout does not carry are kept).</summary>
        public void CopyTo(ActLightingPreset target)
        {
            target.sunColor = EnvironmentLayout.Col(sunColor, target.sunColor);
            target.sunIntensity = sunIntensity;
            target.sunEuler = EnvironmentLayout.Vec(sunEuler, target.sunEuler);
            target.ambientSky = EnvironmentLayout.Col(ambientSky, target.ambientSky);
            target.ambientEquator = EnvironmentLayout.Col(ambientEquator, target.ambientEquator);
            target.ambientGround = EnvironmentLayout.Col(ambientGround, target.ambientGround);
            target.fogColor = EnvironmentLayout.Col(fogColor, target.fogColor);
            target.fogDensity = fogDensity;
            target.rimColor = EnvironmentLayout.Col(rimColor, target.rimColor);
            target.additionalLightTint = EnvironmentLayout.Col(additionalLightTint, target.additionalLightTint);
            target.godRayColor = EnvironmentLayout.Col(godRayColor, target.godRayColor);
            target.godRayIntensity = godRayIntensity;
            target.particleTint = EnvironmentLayout.Col(particleTint, target.particleTint);
        }
    }

    /// <summary>
    /// One dressing entry. Regular props: piece, x/y/z (pivot), rotY, scale, light. "LightShaft": mesh, x/y/z = top of
    /// the shaft, euler, size [top width, length, top width], color, intensity. "AmbientParticles": type, x/y/z, size.
    /// </summary>
    [Serializable]
    public sealed class LayoutProp
    {
        public const string LightShaftPiece = "LightShaft";
        public const string AmbientParticlesPiece = "AmbientParticles";

        public string piece = "";
        public float x;
        public float y;
        public float z;
        public float rotY;
        public float scale;
        public bool light;
        public string mesh = "";
        public float[] euler = Array.Empty<float>();
        public float[] size = Array.Empty<float>();
        public float[] color = Array.Empty<float>();
        public float intensity;
        public string type = "";

        public Vector3 Position => new(x, y, z);
        public float UniformScale => scale > 0f ? scale : 1f;
    }

    [Serializable]
    public sealed class LayoutPointLight
    {
        /// <summary>Index into LayoutAct.props of the prop that carries the light.</summary>
        public int prop;
        public string piece = "";
        public float[] position = Array.Empty<float>();
        public float[] color = Array.Empty<float>();
        public float intensity;
        public float range;

        /// <summary>Selection priority when an act flags more lights than the per-act budget.</summary>
        public float Weight => intensity * range;
    }
}
